### DISCUSSION TITLE
Is the purpose of configuring sse_configs to register existing MCP server with sse specifications on the MCP Gateway？

### DISCUSSION THREAD

**Discussion by foxyriver** [mcp-ecosystem/mcp-gateway#51] [Q&A]
Is the purpose of configuring sse_configs to register existing MCP server with sse specifications on the MCP Gateway？

```yaml
sse_configs:
  - name: "web-search"
    url: "http://localhost:5236/web-search"
```

I configured it, but it didn't works
