### ISSUE TITLE
有些参数，例如enum等，在保存的时候会被删除

### ISSUE THREAD

**Issue by chung1912** [mcp-ecosystem/mcp-gateway#18]
保存前的配置
```
args:
      - name: "displays"
        position: "body"
        required: true
        type: "array"
        description: "Specify list"
        items:
          type: "string"
          enum: ["title", "abs"]
        minItems: 1
        uniqueItems: true
        default: ""
```
保存后的配置
```
args:
      - name: displays
        position: body
        required: true
        type:  array
        description: Specify list
        default: ""
```
关于数组的一些配置都丢失了，我的情况是需要限定enum中数组选项
并且default也不能["title"]这样来写默认配置
