### ISSUE TITLE
配置文件不能读取环境变量，而是当成了字符串处理

### ISSUE THREAD

**Issue by chung1912** [mcp-ecosystem/mcp-gateway#28]
我是这样写的：
```
config:
        Authorization: Bearer ${AUTH_TOKEN}
        Cookie: fastapi
        EndpointBaseURL: ${BASE_URL}
```
请求的时候报错如下：
`Error: failed to execute request: Get "$%7BASE_URL%7D/abc/efg?abcd=xxxxxxxx": unsupported protocol scheme "`，可以看出来，直接当成字符串处理了，没有识别为环境变量的值
