### ISSUE TITLE
初始化系统后登录，调用后端接口还是显示401

### ISSUE THREAD

**Issue by dqx-eterning** [mcp-ecosystem/mcp-gateway#31]
拉取最新的镜像，初始化系统后，无法登录

**Comment by dqx-eterning** [comment]
/api/auth/login 登陆后，401的是这个地址/api/mcp-servers

**Comment by iFurySt** [comment]
![Image](https://github.com/user-attachments/assets/25555d01-ef2c-48b2-9acc-57852f39a584)


这个升级增加了auth相关配置，若是旧的配置麻烦手动增加到旧的配置，再重启试试

```
# JWT configuration
jwt:
  secret_key: "${APISERVER_JWT_SECRET_KEY:Pls-Change-Me!}"  # Change this in production
  duration: "${APISERVER_JWT_DURATION:24h}"                  # Token duration
```

https://github.com/mcp-ecosystem/mcp-gateway/blob/b9732bc47439a00c2d1fee60bef2f9ec392a51ca/configs/apiserver.yaml#L67C1-L70C78
