### ISSUE TITLE
MCP 服务无响应

### ISSUE THREAD

**Issue by wuhunyu** [mcp-ecosystem/mcp-gateway#4]
看下配置，文档没有介绍具体的配置项，下面是仿照修改，导入系统没有问题
```yml
routers:
  - server: "v7"
    prefix: "/api/portal"
    cors:
      allowOrigins:
        - "*"
      allowMethods:
        - "GET"
        - "POST"
        - "OPTIONS"
      allowHeaders:
        - "Content-Type"
        - "Authorization"
        - "Mcp-Session-Id"
      exposeHeaders:
        - "Mcp-Session-Id"
      allowCredentials: true

servers:
  - name: "v7"
    namespace: "v7"
    description: "行云堡垒-v7"
    allowedTools:
      - "getOpenAuthConfig"
      - "isLogin"
    config:
      Cookie: 123

tools:
  - name: "getOpenAuthConfig"
    description: "获取系统当前支持的授权登录方式配置"
    method: "GET"
    endpoint: "https://*.com.cn/api/portal/login/getOpenAuthConfig"
    headers:
      Content-Type: "application/json"
    args:
      - name: "t"
        position: "query"
        required: true
        type: "int"
        description: "时间戳"
        default: "1745568024860"
    responseBody: |-
      {
        "code": "{{.Response.code}}",
        "success": "{{.Response.success}}",
        "msg": "{{.Response.msg}}",
        "authType": "{{.Response.data.authType}}",
        "exclusive": "{{.Response.data.exclusive}}",
        "ssoUrl": "{{.Response.data.ssoUrl}}"
      }

  - name: "isLogin"
    description: "判断当前用户是否已经登录"
    method: "GET"
    endpoint: "https://*.com.cn/api/portal/login/getLogin"
    args:
      - name: "t"
        position: "query"
        required: true
        type: "int"
        description: "时间戳"
        default: "1745568024861"
    responseBody: |-
      {
        "code": "{{.Response.code}}",
        "success": "{{.Response.success}}",
        "msg": "{{.Response.msg}}",
        "isLogged": "{{.Response.data.isLogged}}"
      }
```

#### 现象

图中的第一次有响应的回复是没有使用mcp时回复的，可以证明调用LLM没问题。我使用的是 deepseek v3，也是有 tool 能力的
![Image](https://github.com/user-attachments/assets/75a485bb-1f6c-4d03-921a-6a310cffd13e)

#### 换用其它客户端

这里用的是 cherry studio，也无法启用捏

![Image](https://github.com/user-attachments/assets/3d9a3187-0dc6-4e12-ae25-a6c3c0f35be5)
