### ISSUE TITLE
请求方式为multipart/form-data应该怎么书写？

### ISSUE THREAD

**Issue by chung1912** [mcp-ecosystem/mcp-gateway#41]
请求方式为multipart/form-data应该怎么书写？

**Comment by iFurySt** [comment]
具体是什么场景呢？

**Comment by chung1912** [comment]
> 具体是什么场景呢？

上游api请求体不是json，是form-data的方式，比如：

![Image](https://github.com/user-attachments/assets/19af8413-ee9b-4882-a21e-0d7490f08e4c)

**Comment by iFurySt** [comment]
已支持：
https://github.com/mcp-ecosystem/mcp-gateway/commit/3e2791451e227f44ad131575292a0f3ed46fc88a

使用示例
```yaml
  - name: "update_user_avatar"
    description: "Update user avatar using a URL via multipart form"
    method: "POST"
    endpoint: "http://localhost:5236/users/{{.Args.email}}/avatar"
    headers:
      Authorization: "{{.Request.Headers.Authorization}}"
      Cookie: "{{.Config.Cookie}}"
    args:
      - name: "email"
        position: "path"
        required: true
        type: "string"
        description: "Email of the user"
        default: ""
      - name: "url"
        position: "form-data"
        required: true
        type: "string"
        description: "The avatar image URL"
        default: ""
    responseBody: |-
      {
        "message": "{{.Response.Data.message}}",
        "avatarUrl": "{{.Response.Data.avatarUrl}}"
      }
```

主要通过`position: "form-data"`自动识别转化

效果：

<img width="931" alt="Image" src="https://github.com/user-attachments/assets/9b719ba3-ce7a-4a79-9659-b14cabf9d6c0" />

等价于直接请求

<img width="954" alt="Image" src="https://github.com/user-attachments/assets/43d77800-8f05-42a7-9d7f-a02fe5e53245" />
