### ISSUE TITLE
Support grouping multi MCP servers under one route prefix / 支持将多个 MCP Server 聚合到同一个路由前缀下进行分组管理

### ISSUE THREAD

**Issue by iFurySt** [mcp-ecosystem/mcp-gateway#63]
Currently, one /prefix route maps to a single MCP server.
We plan to support mapping multiple MCP servers to a single prefix, effectively enabling grouping and aggregation.

This allows all tools under those servers to be merged and exposed through the same route, which is useful for scenarios where consumers don’t care about which MCP server the tool belongs to—they just need a unified toolset.

This feature helps simplify management by abstracting away server details and enabling dimensionality reduction on MCP server complexity.

--- 

目前一个 /prefix 路由只能对应一个 MCP Server。

我们希望支持将多个 MCP Server 聚合到同一个前缀下，实现分组功能。这可以将多个 MCP Server 的 tools 合并挂载在一个路径下，对使用者来说可以只关注 tools 而无需关心底层 Server 结构。

这个功能对于“只关心工具集、不关心 MCP Server 数量和来源”的场景非常有用，也有助于对 MCP Server 数量做降维管理。

---

We might consider evolving from

```yaml
routers:
  - server: "mock-user-svc"
    prefix: "/mcp/user"
```

to

```yaml
routers:
  - servers:
      - "mock-user-svc"
      - "mock-order-svc"
    prefix: "/mcp/user"
```
